spring:
  application:
    name: learning
  profiles:
    active: ${LC_PROFILE:develop}
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:${LC_DB_PORT}/${LC_DB_SCHEMA}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${LC_DB_USERNAME}
    password: ${LC_DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: db.changelog/changelog.yml
    database-change-log-table: liquibase_databasechangelog
    database-change-log-lock-table: liquibase_databasechangeloglock
    contexts: '!exampleData'
    parameters:
      schema:
        name: ${LC_DB_SCHEMA}
        profile: ${LC_PROFILE:develop}
      data-type:
        id: uuid
        user-id: varchar(255)
      column:
        created: created
        updated: updated
        created-by: created_by
        updated-by: updated_by

  data:
    rest:
      base-path: /api

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB


---

# Develop Properties
spring:
  config:
    activate:
      on-profile: develop
  liquibase:
    contexts: 'exampleData'
    parameters:
      example:
        user-id:
          - 1dbb034b-675b-4be3-98dc-a8ef0422ff29
          - 6dfe3a23-cb90-4dec-a39d-205df1bbd503
          - 6a36ff3a-83ac-4c75-a7d2-f901d3b46888
        type-id:
          - 64f6331e-11f5-456d-afed-518451ec1eca
          - 55ce92df-199c-42f2-a32f-dc6c12de8581
        deck-id:
          - d14cd912-3f45-48d9-bf8d-454d1d2ac5b9
          - b99f14b7-8071-4859-968b-11023a98b497
          - 7aaf600c-77f6-4e99-a557-0f0a9dd19357