spring:
  application:
    name: learning
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:${LC_DB_PORT}/${LC_DB_SCHEMA}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${LC_DB_USERNAME}
    password: ${LC_DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: db.changelog/changelog.yml
    database-change-log-table: liquibase_databasechangelog
    database-change-log-lock-table: liquibase_databasechangeloglock
    parameters:
      schema:
        name: ${LC_DB_SCHEMA}
      data-type:
        id: uuid
        user-id: varchar(255)
      column:
        created: created
        updated: updated
        created-by: created_by
        updated-by: updated_by
