spring:
  application:
    name: learning
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/learning_cards
    username: DB_USR_1
    password: x#2M8e)#m0@V1J+>J(!3
  liquibase:
    enabled: true
    change-log: db.changelog/changelog.yml
    database-change-log-table: liquibase_databasechangelog
    database-change-log-lock-table: liquibase_databasechangeloglock
    parameters:
      schema:
#        TODO: will be changed to use environment variables
        name: learning_cards
      data-type:
        id: uuid
        user-id: varchar(255)
      column:
        created: created
        updated: update
        created-by: created_by
        updated-by: updated_by
